### PR TITLE
fix: crash for getting non existing image for a contact

### PR DESCRIPTION
**Pull request by amrgetment**
fix: crash for getting a non-existing image for a contact

the crash

```
I/flutter (21932): ----------------FIREBASE CRASHLYTICS----------------
I/flutter (21932): PlatformException(, No photo file found for ID 0, java.io.FileNotFoundException: No photo file found for ID 0, null)
I/flutter (21932): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
I/flutter (21932): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
I/flutter (21932): <asynchronous suspension>
I/flutter (21932): #2      ContactsPhotosService._getContactImage (package:example/features/contacts_import/data/services/contacts_photos_service.dart:115:9)
I/flutter (21932): <asynchronous suspension>
```

### CODE REVIEW

**Comment by amrgetment** [comment]
@s0nerik Could you check my PR?

**Comment by s0nerik** [comment]
Thanks for your contribution, @amrgetment! I'll look into it somewhere closer to the weekend.

Sorry for the delay, just lost the previous notification somehow...

**Comment by amrgetment** [comment]
No worries, I understand you’re  busy in work, good luck and thanks for your effort in this library

**Comment by s0nerik** [comment]
I've applied the fix from this PR in [v3.1.4](https://pub.dev/packages/fast_contacts/changelog#314). Thanks for your contribution!

**Pull request closed without merging**
